In [2]:
import pandas as pd


print(pd.read_csv('results_all.csv'))

      Model  Accuracy      F1  ROC-AUC  Precision           Saved_Time
0  CatBoost    0.8294  0.7817   0.8830     0.7671  2026-06-04 13:00:18
1   XGBoost    0.8395  0.7935   0.8870     0.7834  2026-06-04 14:53:42
2       MLP    0.8159  0.7310   0.8678     0.8344  2026-06-10 15:22:05

In [3]:
from core import fit_preprocessor, transform_preprocessor

import joblib
import pandas as pd
from sklearn.pipeline import Pipeline
import pickle


df_train_raw = pd.read_csv('train.csv')

X_train, Y_train, preprocess_params = fit_preprocessor(df_train_raw)

import pickle
with open('preprocess_params.pkl', 'wb') as f:
    pickle.dump(preprocess_params, f)

In [4]:
X_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   891 non-null    int64
 1   Pclass        891 non-null    int64
 2   Sex           891 non-null    int64
 3   Age           891 non-null    float64
 4   Fare          891 non-null    float64
 5   Cab_count     891 non-null    int64
 6   Emb_Q         891 non-null    int64
 7   Emb_S         891 non-null    int64
 8   Deck_tar_enc  891 non-null    float64
 9   Designation   891 non-null    int64
 10  Family        891 non-null    int64
 11  Ticket_uniq   891 non-null    int64
dtypes: float64(3), int64(9)
memory usage: 83.7 KB

In [5]:
with open('preprocess_params.pkl', 'rb') as f:
    preprocess_params = pickle.load(f)

df_test_raw = pd.read_csv('test.csv')
X_test = transform_preprocessor(df_test_raw, preprocess_params)

In [6]:
X_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   418 non-null    int64
 1   Pclass        418 non-null    int64
 2   Sex           418 non-null    int64
 3   Age           418 non-null    float64
 4   Fare          418 non-null    float64
 5   Cab_count     418 non-null    int64
 6   Emb_Q         418 non-null    int64
 7   Emb_S         418 non-null    int64
 8   Deck_tar_enc  418 non-null    float64
 9   Designation   418 non-null    int64
 10  Family        418 non-null    int64
 11  Ticket_uniq   418 non-null    int64
dtypes: float64(3), int64(9)
memory usage: 39.3 KB

In [7]:
X_test['Designation'].unique()

array([0, 1, 2, 3, 4])

In [8]:
X_test

,PassengerId,Pclass,Sex,Age,Fare,Cab_count,Emb_Q,Emb_S,Deck_tar_enc,Designation,Family,Ticket_uniq
0,892,3,1,34.5,7.8292,0,1,0,0.300,0,0,0
1,893,3,0,47.0,7.0000,0,0,1,0.300,1,1,0
2,894,2,1,62.0,9.6875,0,1,0,0.300,0,0,0
3,895,3,1,27.0,8.6625,0,0,1,0.300,0,0,0
4,896,3,0,22.0,12.2875,0,0,1,0.300,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,1,25.0,8.0500,0,0,1,0.300,0,0,0
414,1306,1,0,39.0,108.9000,1,0,0,0.593,4,0,0
415,1307,3,1,38.5,7.2500,0,0,1,0.300,0,0,0
416,1308,3,1,25.0,8.0500,0,0,1,0.300,0,0,0
417,1309,3,1,25.0,22.3583,0,0,0,0.300,3,2,0

In [12]:
from core import X_train

In [15]:
X_train

,Pclass,Sex,Age,Fare,Cab_count,Emb_Q,Emb_S,Deck_tar_enc,Designation,Family,Ticket_uniq
0,3,1,22.0,7.2500,0,0,1,0.296,0,1,1
1,1,0,38.0,71.2833,1,0,0,0.646,1,1,1
2,3,0,26.0,7.9250,0,0,1,0.299,2,0,1
3,1,0,35.0,53.1000,1,0,1,0.556,1,1,0
4,3,1,35.0,8.0500,0,0,1,0.305,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
886,2,1,27.0,13.0000,0,0,1,0.298,4,0,1
887,1,0,19.0,30.0000,1,0,1,0.711,2,0,1
888,3,0,21.5,23.4500,0,0,1,0.302,2,3,0
889,1,1,26.0,30.0000,1,0,0,0.596,0,0,1
890,3,1,32.0,7.7500,0,1,0,0.296,0,0,1